version: "3.7"

services:
  uicadb:
    image: postgres
    environment:
      POSTGRES_USER: uica
      POSTGRES_PASSWORD: uica
      POSTGRES_DB: uica-app
    ports:
      - "5555:5432"
    volumes:
      - ./pgdb/data:/var/lib/postgresql/data
